repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
        types: [python, yaml, toml, markdown, json]
        stages: [commit, push, manual]
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        types: [python, yaml, toml, markdown, json]
        stages: [commit, push, manual]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.7"
    hooks:
      - id: ruff-format
        types: [python]
  - repo: local
    hooks:
      #- id: bandit
      #  name: bandit
      #  entry: bandit
      #  language: system
      #  types: [python]
      #  require_serial: true
      #  args: ["-c", "bandit.yml"]
      #- id: black
      #  name: black
      #  entry: black
      #  language: system
      #  types: [python]
      #  require_serial: true
      #- id: darglint
      #  name: darglint
      #  entry: darglint
      #  language: system
      #  types: [python]
      #  stages: [manual]
      #- id: flake8
      #  name: flake8
      #  entry: flake8
      #  language: system
      #  types: [python]
      #  require_serial: true
      #  args: [--darglint-ignore-regex, .*]
      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: system
        types_or: [cython, pyi, python]
        args: ["--filter-files"]
      - id: pyupgrade
        name: pyupgrade
        description: Automatically upgrade syntax for newer versions.
        entry: pyupgrade
        language: system
        types: [python]
        args: [--py310-plus]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [yaml, markdown, json, toml]
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.6"
    hooks:
      - id: codespell
        args: ["-L", "dipoleq,garnier"]
        types: [python]
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: "v0.16"
    hooks:
      - id: validate-pyproject
        additional_dependencies: ["validate-pyproject-schema-store[all]"]
 

