on: [push]

jobs:
    build_on_ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: Dependencies
              uses: daaku/gh-action-apt-install@v4
              with:
                packages: zlib1g-dev libjpeg-dev libhdf4-dev
            - name: Checkout on Ubuntu
              uses: actions/checkout@v2
              with:
                fetch-depth: 1
            - name: Build on Ubuntu
              uses: threeal/cmake-action@v1.2.0
              with:
                run-build: true
